version: 2
jobs:
  build_customer:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run:
          name: Build and push image
          run: |
            mvn clean package
            docker build . -t marcosx/customer:v1
            docker login -u $DOCKER_USER -p $DOCKER_PWD
            docker push marcosx/customer:v1
  deploy_customer:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Deploy to cluster
          run: |
            echo ${GCLOUD_SERVICE_KEY} > gcloud-key.json
            gcloud auth activate-service-account --key-file=gcloud-key.json
            gcloud container clusters get-credentials "dev-playground" --project "g-gke-clusters" --zone "us-central1-a"
            kubectl apply -f customer/kubernetes/Deployment.yml -n sample-app
            kubectl apply -f customer/kubernetes/Service.yml -n sample-app
workflows:
  version: 2
  customer:
    jobs:
      - build_customer
      - deploy_customer:
        requires:
          - build_customer
